// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mummdswkszajfwuumome.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11bW1kc3drc3phamZ3dXVtb21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTAzMzgsImV4cCI6MjA2NTM4NjMzOH0.7ISjw7w7mZ_pE_5j_gmxWmSYYOwIi7DoUT9AYsxh5rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);